apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: handika
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: docker.io/vhandika/laravel-app:v12
        ports:
        - containerPort: 8000
          name: laravel
        envFrom:
        - secretRef:
            name: laravel-app-secret
        - configMapRef:
            name: laravel-app-cm

---

apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: handika
spec:
  selector:
    app: laravel
  ports:
  - port: 8000
    targetPort: 8000
    name: laravel
  type: ClusterIP
