apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
data:
  DB_HOST: "bXlzcWw="
  DB_CONNECTION: "bXlzcWw="
  DB_DATABASE: "bGFyYXZlbF9kYg=="
  DB_USERNAME: "cm9vdA=="
  DB_PORT: "MzMwNg=="
  DB_PASSWORD: "cm9vdA=="
